### ISSUE TITLE
Raise an error when stitching a reprint with different products, platforms or classification.

### ISSUE THREAD

**Issue by Illidanz** [vgmdb/tracker#174]
Also maybe other fields like classification.

Also fix the current reprints in the database that have the fields different/empty.

**Comment by Kenneth-T-Moore** [comment]
Instead of making them the same, it should raise an error so that the staff member can look them over more carefully and decide what platforms and products are correct.

**Comment by nstz0** [comment]
That's not compatible with how the reprint system works. It would be overwritten by someone editing the field on the parent.

Additionally, I'm not really sure why a reprint would need to have different platforms from the parent since our guideline is "For original soundtracks, please only select the platform that the music comes from, even if the game appeared on multiple platforms. (e.g. Don't select PSX for the new 1991 Final Fantasy IV Soundtrack.)".

Edit: Actually nevermind, I think I completely misunderstood the comment. I think what you were saying is that they should still be made the same, just not automatically.
