### ISSUE TITLE
Slow-updating view counter on organization and product pages

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#360]
Unlike the artist and album view counters which update instantly upon new page views, product and organization pages take a long time to be updated. Tested by viewing pages with different IPs and seeing the change in view count. The album and artist pages instantly increased in view count as expected. The product and organization pages did not.

**Comment by Illidanz** [comment]
I've checked the view tracker bot and there are no difference between entry types, what probably happens is that for those types that are less visited and don't get hits for a while (which doesn't happen for album/artist), the tracker bot shuts down temporarily since it's not doing any work and gets restarted after a while.
