### ISSUE TITLE
Albums can be added to the same folder multiple times in collections

### ISSUE THREAD

**Issue by vgmcal** [vgmdb/tracker#449]
![image](https://user-images.githubusercontent.com/74626685/146566767-9650c0bf-64b9-41ae-be67-bf816ec2b5f7.png)

**Comment by jsutan** [comment]
I don't think this is a bug, there should be a way to add an album to your collection multiple times in case you own multiple. Right now there's no intuitive way to do that but it is technically possible if you add by albumid manually.

Perhaps just change this view to only show distinct instead of all.

**Comment by Illidanz** [comment]
I agree, we should have more metadata in collections, but this is a use case for someone so we should do that before changing that behavior.

In the meantime I've improved the Owned by page so it doesn't show the same user more than once.
