### ISSUE TITLE
Show differences from currently linked artists while previewing a draft on a entry

### ISSUE THREAD

**Issue by Illidanz** [vgmdb/tracker#70]
Especially useful for moderating an entry with a lot of artist links to check what was added/removed quickly.

**Comment by Kenneth-T-Moore** [comment]
Diff method 1:  For drafts that edit artists that have already been converted to use the new roles, a standard diff would work (show all artistIDs that were removed, show all artistIDs that were added, show all artistIDs with changed metadata.)

Diff method 2: For drafts that replace legacy artists, I think the main concern is losing old information rather than an exhaustive list of the changes, because we expect a ton of new credits due to the new roles. A simpler diff can be used to find missing artists, taking into account the old 4-field structure and how they map to new roles.  (Though we also need to do this with a handful of other manually added legacy roles.)

```
Outer Loop: for each legacy artist field

Inner Loop: for each artistID in that field

  Find all role credits for that artistID in the new credits if they match the group (e.g., Composer(legacy) is in the Composer group.)

  If there are any matches, loop over new roles that match ID:
    output the following in gray (de-emphasized)
    Artist Name (ID): new role name

    Note: I think it might be worthwhile to check if any aliases were changed here too, but it can get messy with aliases that don't have a page.

  If there are no matches, output the following in white (emphasized)
  Artist Name (ID): MISSING
```
