### ISSUE TITLE
Sugestion change composer

### ISSUE THREAD

**Issue by romanoh** [vgmdb/tracker#89]
Sometimes it says:
Composed By
Composed
Composer
Composers

i make a suggestion to make one name only, like: Composer.

**Comment by Illidanz** [comment]
This is due to a recent change we made to allow any number of roles to be linked to entries, which was only recently applied to albums.

If this is for parsing purposes, you can find the (current) list of possible composer aliases here: https://vgmdb.net/role/35
Do note that some old "composer" credits are now changed to Music, depending on how they're credited in the release.
#76 might also make it easier to parse the artists since you can just look for the artist ID (35 in that case).

**Comment by romanoh** [comment]
I never noticed the roles section thank you.
